CRC_ALGORITHMS = {
    "CRC-4/ITU":{
        "width": 4,
        "poly": 0x03,
        "crc_init": 0x00,
        "refin": True,
        "refout": True,
        "xorout": 0x00,
    },
    "CRC-5/EPC":{
        "width": 5,
        "poly": 0x09,
        "crc_init": 0x09,
        "refin": False,
        "refout": False,
        "xorout": 0x00,
    },
    "CRC-5/ITU":{
        "width": 5,
        "poly": 0x15,
        "crc_init": 0x00,
        "refin": True,
        "refout": True,
        "xorout": 0x00,
    },
    "CRC-5/USB":{
        "width": 5,
        "poly": 0x05,
        "crc_init": 0x1F,
        "refin": True,
        "refout": True,
        "xorout": 0x1F,
    },
    "CRC-6/ITU":{
        "width": 6,
        "poly": 0x03,
        "crc_init": 0x00,
        "refin": True,
        "refout": True,
        "xorout": 0x00,
    },
    "CRC-7/MMC":{
        "width": 7,
        "poly": 0x09,
        "crc_init": 0x00,
        "refin": False,
        "refout": False,
        "xorout": 0x00,
    },
    "CRC-8":{
        "width": 8,
        "poly": 0x07,
        "crc_init": 0x00,
        "refin": False,
        "refout": False,
        "xorout": 0x00,
    },
    "CRC-8/ITU":{
        "width": 8,
        "poly": 0x07,
        "crc_init": 0x00,
        "refin": False,
        "refout": False,
        "xorout": 0x55,
    },
    "CRC-8/ROHC":{
        "width": 8,
        "poly": 0x07,
        "crc_init": 0xFF,
        "refin": True,
        "refout": True,
        "xorout": 0x00,
    },
    "CRC-8/MAXIM":{
        "width": 8,
        "poly": 0x31,
        "crc_init": 0x00,
        "refin": True,
        "refout": True,
        "xorout": 0x00,
    },
    "CRC-16/IBM":{
        "width": 16,
        "poly": 0x8005,
        "crc_init": 0x0000,
        "refin": True,
        "refout": True,
        "xorout": 0x0000,
    },
    "CRC-16/MAXIM":{
        "width": 16,
        "poly": 0x8005,
        "crc_init": 0x0000,
        "refin": True,
        "refout": True,
        "xorout": 0xFFFF,
    },
    "CRC-16/USB":{
        "width": 16,
        "poly": 0x8005,
        "crc_init": 0xFFFF,
        "refin": True,
        "refout": True,
        "xorout": 0xFFFF,
    },
    "CRC-16/MODBUS":{
        "width": 16,
        "poly": 0x8005,
        "crc_init": 0xFFFF,
        "refin": True,
        "refout": True,
        "xorout": 0x0000,
    },
    "CRC-16/CCITT":{
        "width": 16,
        "poly": 0x1021,
        "crc_init": 0x0000,
        "refin": True,
        "refout": True,
        "xorout": 0x0000,
    },
    "CRC-16/CCITT-FALSE":{
        "width": 16,
        "poly": 0x1021,
        "crc_init": 0xFFFF,
        "refin": False,
        "refout": False,
        "xorout": 0x0000,
    },
    "CRC-16/X25":{
        "width": 16,
        "poly": 0x1021,
        "crc_init": 0xFFFF,
        "refin": True,
        "refout": True,
        "xorout": 0xFFFF,
    },
    "CRC-16/XMODEM":{
        "width": 16,
        "poly": 0x1021,
        "crc_init": 0x0000,
        "refin": False,
        "refout": False,
        "xorout": 0x0000,
    },
    "CRC-16/DNP":{
        "width": 16,
        "poly": 0x3D65,
        "crc_init": 0x0000,
        "refin": True,
        "refout": True,
        "xorout": 0xFFFF,
    },
    "CRC-32":{
        "width": 32,
        "poly": 0x04C11DB7,
        "crc_init": 0xFFFFFFFF,
        "refin": True,
        "refout": True,
        "xorout": 0xFFFFFFFF,
    },
    "CRC-32/MPEG-2":{
        "width": 32,
        "poly": 0x04C11DB7,
        "crc_init": 0xFFFFFFFF,
        "refin": False,
        "refout": False,
        "xorout": 0x00000000,
    },
}